name: Test posting comment
on: [pull_request]
env:
  TERRAFORM_PLAN_FILE_NAME: tf_plan

jobs:
  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Store terraform plan in environment variable
      id: terraform-plan
      run: |
        cat  >> ${{ env.TERRAFORM_PLAN_FILE_NAME }} <<EOF
        line 1 this is fake terraform plan
        line 2 of the plan
        EOF
        
        echo "TERRAFORM_PLAN<<EOF" >> $GITHUB_ENV
        cat "${{ env.TERRAFORM_PLAN_FILE_NAME }}" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Post plan comment to pull request
      uses: actions/github-script@v6
      env:
        TERRAFORM_PLAN: ${{ env.TERRAFORM_PLAN }}
        TERRAFORM_PLAN_STEP_OUTCOME: ${{ steps.terraform-plan.outcome }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const script = require('./scripts/upload_plan.js');
          await script(github, context);
